development:
  adapter: postgresql
  encoding: unicode
  database: wobb_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wobb_test
  pool: 5
  username:
  password:
